language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.0
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services

script: ./gradlew build

notifications:
  email: false

sudo: false
